version: '3.9'
services:
  carsinventory:
    build: .
    image: carsinventory
    ports:
      - 3050:3050
    depends_on:
      - mongo_db
    networks:
      - inventory-network

  mongo_db:
    container_name: cars_db_container
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    volumes:
      - cars_mongo_data:/data/db
    networks:
      - inventory-network

volumes:
  cars_mongo_data: {}

networks:
  inventory-network:
    driver: bridge